### PR TITLE
fixed links on user menu, commented non yet supported items

### LINKED ISSUE #155: Finish open issues in user menu
**Describe the feature you'd like to see included in Tree Mapper App.**
Finish open issues in user menu:

- [ ] Profile edit link opens in other app, e.g. browser, but only shows an 404 error. 
- [ ] The further three menu items do nothing when clicked (maybe show some nice "not yet implemented" alert or notification)
- [ ] Imprint ("Impressum") is missing
- [ ] Privacy Policy ("Datenschutzerklärung") opens link in other app (clarify if this has to be shown within the app for legal reasons!)
- [ ] Terms ("AGB") do not show or open any link to terms.

Be aware links might also be opened by a native Treecounter-App installed!

Simulator Screen Shot - iPhone 11 - 2021-01-23 at 11 52 54

Probably needs some specification as what should be done for the various menu items.

### PR DESCRIPTION
**Pull request by norbertschuler**
Fixes #155

Changes in this pull request:
- [x] Profile edit link opens in other app, e.g. browser, but only shows an 404 error. 
- [x] The further three menu items do nothing when clicked (maybe show some nice "not yet implemented" alert or notification)
- [x] Imprint ("Impressum") is missing
- [x] Privacy Policy ("Datenschutzerklärung") opens link in other app (clarify if this has to be shown within the app for legal reasons!)
- [x] Terms ("AGB") do not show or open any link to terms.

Simulator Screen Shot - iPhone 11 - 2021-02-04 at 15 18 44Simulator Screen Shot - iPhone 11 - 2021-02-04 at 16 29 41Simulator Screen Shot - iPhone 11 - 2021-02-04 at 16 29 45

### CODE REVIEW

File: app/components/ProfileModal/index.js [hunk 1]
```diff
@@ -87,16 +93,16 @@ const ProfileModal = ({
...
+    // {
+    //   media: 'cloud-upload-alt',
+    //   mediaType: 'icon',
+    //   text: 'all_backed_up',
+    // },
+    // {
+    //   media: 'map-marked',
+    //   mediaType: 'icon',
+    //   text: 'manage_offline',
+    // },
```
Comment (norbertschuler) [inline app/components/ProfileModal/index.js:105]: I commented these menu items unless we really want to support them - both is accessible otherwise.

Comment (ankitecd) [reply app/components/ProfileModal/index.js:105]: Backup menu item is removed in activity log PR and manage offline maps can be commented as of now.

**Comment by norbertschuler** [comment]
@sagararyal please check.
