### PR TITLE
Feature/unzip fix

### LINKED ISSUE #217: App seems "frozen" at first start for some seconds
**Describe the bug**
At the first start after installing the app, the app takes some time (e.g. almost 10 seconds on a Nexus 7 tablet with Android 6) before the user can interact with the UI. Before that the app seems to be frozen. There must be some UI blocking process running (maybe downloading and unpacking the species list)?

**To Reproduce**
1. Delete and install app
2. Start the app
3. See behavior

**Expected behavior**
UI should not be blocked after starting the app for the first time or show some progress indicator until the app can be used.

**What actually happens**
UI is blocked. App seems to be frozen. Especially on older devices.

**Smartphone (please complete the following information):**
- Device: Google Nexus 7
- OS: Android 6
- Tree Mapper App Version: 1.0.0

### PR DESCRIPTION
**Pull request by ankitecd**
Fixes #217 

Changes in this pull request:
- Added loading screen while species are updating.
- updated user avatar, PFP logo

### CODE REVIEW

File: app/components/ProfileModal/index.js [hunk 1]
```diff
@@ -86,27 +88,40 @@ const ProfileModal = ({
...
+              <View style={styles.logoContainer}>
+                <SvgXml xml={logo} />
+              </View>
             </View>
             <View style={styles.profileSection1}>
-              <Image
-                style={{ width: 50, height: 50, marginHorizontal: 10, borderRadius: 50 }}
-                source={{ uri: avatar }}
-              />
+              {avatar ? (
```
Comment (norbertschuler) [inline app/components/ProfileModal/index.js:112]: `avatar` probably is never undefined because of the default image is still used at https://github.com/Plant-for-the-Planet-org/treemapper/blob/85b08bb4893e32788a10790cd240436f42caccfc/app/components/ProfileModal/index.js#L36-L38

**Review by norbertschuler — COMMENTED** [review]
Database migration is quite fast (if you have few database entries like me) - I almost missed the screen while species download took much longer ;-)

Anyway it works well for me. Just added an issue I found with one place to show the user profile not yet correctly working.

File: app/components/ProfileModal/index.js (hunk 1 above)
Comment (ankitecd) [reply app/components/ProfileModal/index.js:108]: ohh thanks. Fixed it

**Review by norbertschuler — APPROVED** [review]
LGFM
