### PR TITLE
Feature/bug fixes

### LINKED ISSUE #254: App got stuck if trying to download map without network connection
**Describe the bug**
If you try to download a map when you have no internet connection, the app got stuck.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to download map
2. Click button to download map
3. See error

**Screenshots**
Simulator Screen Shot - iPhone 11 - 2021-03-12 at 15 27 40

**Smartphone (please complete the following information):**
- Device: iPhone 11 simulator
- OS: latest iOS
- Tree Mapper App Version: 1.0.0

### PR DESCRIPTION
**Pull request by tejassonar**
Fixes #254

Changes in this pull request:
- disabled auto upload from #259

### CODE REVIEW

File: app/components/DownloadMap/index.js [hunk 1]
```diff
@@ -88,56 +91,60 @@ const DownloadMap = ({ navigation }) => {
...
+            if (err.message !== 'timeout') {
+              setIsLoaderShow(false);
+              setAreaName('');
+              alert(err.message);
+            }
+          };
+          await MapboxGL.offlineManager.createPack(
+            {
+              name: offllineMapId,
+              styleURL: 'mapbox://styles/sagararl/ckdfyrsw80y3a1il9eqpecoc7',
```
Comment (norbertschuler) [inline app/components/DownloadMap/index.js:131]: @sagararyal are you aware this is a production asset that won't get changed accidentally any more?

**Comment by norbertschuler** [comment]
- [ ] I am getting dozen of MapBox console.error message, but they hopefully will not be posted to Bugsnag in production: `[Sat Mar 27 2021 10:45:54.912]  ERROR    Mapbox error Requesting: (null) failed with error: <MGLNetworkConfiguration: 0x6000036ab480> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 135, "message": "Requesting: (null) failed with error: <MGLNetworkConfiguration: 0x6000036ab480>"}`

Simulator Screen Shot - iPhone 11 - 2021-03-27 at 10 46 06

**Review by norbertschuler — APPROVED** [review]
I had some trouble in my iOS simulator starting it without an internet connection and then switching back on the WiFi in the way the app did not recognized that my device had a valid connection again - after I restarted the app it worked again. I am not sure if that's a problem a my simulator or also on a real iOS device. Otherwise everything seems to work well.

Simulator Screen Shot - iPhone 11 - 2021-03-27 at 10 58 27
