### PR TITLE
added logs & resolved some bugs

### LINKED ISSUE #355: Show uploaded registrations sorted by date
**Describe the feature you'd like to see included in Tree Mapper App.**
Currently the list is unsorted. Let's sort them by date to give some better overview.

This can be done either in the frontend or backend directly in the response from the API call (which I would prefer).

Simulator Screen Shot - iPhone 11 - 2021-05-29 at 12 55 27

### PR DESCRIPTION
**Pull request by tejassonar**
Fixes #355

Changes in this pull request:
- Sorting of inventories with registration Date
- Added height, diameter, and tag id in the inventory list item
- Handled Logout error while not having Network
- Checking of CaptureStatus before adding inventories
- Used Aliases instead of Scientific Species on Inventory overview (Bug)
- added dbLogs wherever necessary

@ankitecd

### CODE REVIEW

File: app/actions/UploadInventory.js [hunk 1]
```diff
@@ -456,7 +486,14 @@ const updateSampleTreeByIndex = (
 
     updateInventory({ inventory_id: inventory.inventory_id, inventoryData })
       .then(resolve)
-      .catch(reject);
+      .catch((err) => {
+        console.error(err);
```
Comment (norbertschuler) [inline app/actions/UploadInventory.js:490]: Maybe removed console.log

File: app/actions/species.js [hunk 2]
```diff
@@ -232,11 +239,19 @@ export const getBase64ImageFromURL = async (specieImage) => {
...
                 console.error(err.message);
               });
             })
-            .catch((err) => console.error('Error while reading file image'));
+            .catch((err) => {
+              dbLog.error({
+                logType: LogTypes.MANAGE_SPECIES,
+                message: 'Error while reading file image',
+              });
+              console.error('Error while reading file image');
```
Comment (norbertschuler) [inline app/actions/species.js:252]: Maybe remove console.log

File: app/components/SelectSpecies/index.js [hunk 3]
```diff
@@ -66,15 +66,15 @@ const SelectSpecies = () => {
...
+            aliases: specie.aliases,
             treeCount: 1,
           },
         ],
       });
     } else {
       let updatedSampleTrees = [...inventory.sampleTrees];
       updatedSampleTrees[inventory.completedSampleTreesCount].specieId = specie.guid;
-      updatedSampleTrees[inventory.completedSampleTreesCount].specieName = specie.scientificName;
+      updatedSampleTrees[inventory.completedSampleTreesCount].specieName = specie.aliases;
```
Comment (norbertschuler) [inline app/components/SelectSpecies/index.js:77]: Sorry, I can't see where this applies in the UI? I always see the scientific name in my tests everywhere I work with species.

Comment (norbertschuler) [reply app/components/SelectSpecies/index.js:77]: My fault. Got it.

**Review by norbertschuler — APPROVED** [review]
Looks good for me.

**Comment by norbertschuler** [comment]
If you change your specie alias multiple times, you can create different registrations for the same scientific specie with different aliases:

Simulator Screen Shot - iPhone 11 - 2021-07-06 at 14 29 39

File: app/repositories/inventory.js [hunk 4]
```diff
@@ -113,6 +113,7 @@ export const getInventoryByStatus = (status1, status2, status3) => {
           inventory = inventory.filtered(
             `status == "${status1}" || status == "${status2}" || status == "${status3}"`,
           );
+          inventory = inventory.sorted('registrationDate', true);
```
Comment (ankitecd) [inline app/repositories/inventory.js:116]: Sort for all the status while fetching inventory

File: app/actions/UploadInventory.js [hunk 5]
```diff
@@ -67,6 +67,10 @@ const changeStatusAndUpload = async (response, oneInventory, dispatch) => {
                   )
                     .then(() => resolve())
                     .catch((err) => {
+                      dbLog.error({
+                        logType: LogTypes.INVENTORY,
+                        message: `Failed to change inventory status: ${SYNCED} with inventory id: ${oneInventory.inventory_id}. Error at: /action/upload/changeInventoryStatus, -> ${err}`,
+                      });
```
Comment (ankitecd) [inline app/actions/UploadInventory.js:73]: This will throw an error and might crash the app since err is an `object` type and `message` property in realm is a string type

**Review by ankitecd — CHANGES_REQUESTED** [review]
Check for internet connection is not present for auto logout on error like 403 or 401

File: app/actions/UploadInventory.js (hunk 5 above)
Comment (norbertschuler) [reply app/actions/UploadInventory.js:73]: If this is a problem here, maybe other usages of `dbLog` should also be checked?

Comment (norbertschuler) [reply app/actions/UploadInventory.js:73]: Why not use `logStack: JSON.stringify(err)` as used elsewhere for the err object?

Comment (norbertschuler) [reply app/actions/UploadInventory.js:73]: I scanned the codebase and add some missing `logStack` params for `dbLog.error` in https://github.com/Plant-for-the-Planet-org/treemapper/pull/404 (this one not included of course!)

Comment (ankitecd) [reply app/actions/UploadInventory.js:73]: Yes i have asked Tejas to do the same.

**Comment by ankitecd** [comment]
> 
> 
> If you change your specie alias multiple times, you can create different registrations for the same scientific specie with different aliases:

But we pass species id, so this won't be a problem. Also right now even if name is not changed one can register many single tree for same species.

**Review by ankitecd — APPROVED** [review]
Looks
